import type { RenderTarget } from './framebuffer.ts';
import type { RGB } from './color.ts';

/** Add a soft finite-width HDR line to a CPU render target. */
export function addSoftSegment(target:RenderTarget,a:{x:number;y:number},b:{x:number;y:number},color:RGB,radius:number,intensity=1):void { const minX=Math.max(0,Math.floor(Math.min(a.x,b.x)-radius*2)),maxX=Math.min(target.width-1,Math.ceil(Math.max(a.x,b.x)+radius*2)),minY=Math.max(0,Math.floor(Math.min(a.y,b.y)-radius*2)),maxY=Math.min(target.height-1,Math.ceil(Math.max(a.y,b.y)+radius*2));const vx=b.x-a.x,vy=b.y-a.y,ll=vx*vx+vy*vy||1;for(let y=minY;y<=maxY;y++)for(let x=minX;x<=maxX;x++){const t=Math.max(0,Math.min(1,((x-a.x)*vx+(y-a.y)*vy)/ll)),dx=x-(a.x+vx*t),dy=y-(a.y+vy*t),d2=dx*dx+dy*dy,k=Math.exp(-d2/(2*radius*radius))*intensity;if(k<.003)continue;target.plot(x,y,-0.99,{r:color[0]*k,g:color[1]*k,b:color[2]*k,a:1},'add');}}

export function pointSegmentDistance(x:number,y:number,a:{x:number;y:number},b:{x:number;y:number}):number { const vx=b.x-a.x,vy=b.y-a.y,ll=vx*vx+vy*vy||1,t=Math.max(0,Math.min(1,((x-a.x)*vx+(y-a.y)*vy)/ll));return Math.hypot(x-(a.x+vx*t),y-(a.y+vy*t)); }

export function addSoftPoint(target:RenderTarget,x:number,y:number,color:RGB,radius:number,intensity=1):void { const r=Math.max(1,radius),minX=Math.max(0,Math.floor(x-r*2)),maxX=Math.min(target.width-1,Math.ceil(x+r*2)),minY=Math.max(0,Math.floor(y-r*2)),maxY=Math.min(target.height-1,Math.ceil(y+r*2));for(let py=minY;py<=maxY;py++)for(let px=minX;px<=maxX;px++){const d2=(px-x)*(px-x)+(py-y)*(py-y),k=Math.exp(-d2/(2*r*r))*intensity;if(k<.003)continue;target.plot(px,py,-.98,{r:color[0]*k,g:color[1]*k,b:color[2]*k,a:1},'add');}}

/** Illuminate only the portion of an edge near a physical light crossing. */
export function addLocalizedEdgeLight(target:RenderTarget,a:{x:number;y:number},b:{x:number;y:number},focus:{x:number;y:number},color:RGB,radius:number,intensity=1):void { const vx=b.x-a.x,vy=b.y-a.y,ll=vx*vx+vy*vy||1,t=Math.max(0,Math.min(1,((focus.x-a.x)*vx+(focus.y-a.y)*vy)/ll)),center={x:a.x+vx*t,y:a.y+vy*t},half=Math.min(.32,radius/Math.sqrt(ll)),from={x:a.x+vx*Math.max(0,t-half),y:a.y+vy*Math.max(0,t-half)},to={x:a.x+vx*Math.min(1,t+half),y:a.y+vy*Math.min(1,t+half)};addSoftSegment(target,from,to,color,Math.max(1,radius*.12),intensity);addSoftPoint(target,center.x,center.y,color,radius*.28,intensity*.45);}

export interface SpectralRibbonSample { start:{x:number;y:number}; end:{x:number;y:number}; color:RGB; intensity:number }
/** Connect adjacent wavelength paths into one continuously interpolated HDR sheet. */
export function addSpectralRibbon(target:RenderTarget,samples:readonly SpectralRibbonSample[],gain=1):void { const white:RGB=[255,255,255];for(let i=0;i<samples.length-1;i++){const a=samples[i],b=samples[i+1];addGradientTriangle(target,a.start,a.end,b.end,white,a.color,b.color,a.intensity,b.intensity,gain);addGradientTriangle(target,a.start,b.end,b.start,white,b.color,white,a.intensity,b.intensity,gain);}const first=samples[0],last=samples.at(-1);if(first)addSoftSegment(target,first.start,first.end,first.color,1.15,first.intensity*gain*.2);if(last)addSoftSegment(target,last.start,last.end,last.color,1.15,last.intensity*gain*.2); }

function addGradientTriangle(target:RenderTarget,a:{x:number;y:number},b:{x:number;y:number},c:{x:number;y:number},ca:RGB,cb:RGB,cc:RGB,ia:number,ic:number,gain:number):void { const area=edge(a,b,c.x,c.y);if(Math.abs(area)<1e-5)return;const minX=Math.max(0,Math.floor(Math.min(a.x,b.x,c.x))),maxX=Math.min(target.width-1,Math.ceil(Math.max(a.x,b.x,c.x))),minY=Math.max(0,Math.floor(Math.min(a.y,b.y,c.y))),maxY=Math.min(target.height-1,Math.ceil(Math.max(a.y,b.y,c.y)));for(let y=minY;y<=maxY;y++)for(let x=minX;x<=maxX;x++){const w0=edge(b,c,x+.5,y+.5)/area,w1=edge(c,a,x+.5,y+.5)/area,w2=1-w0-w1;if(w0<0||w1<0||w2<0)continue;const longitudinal=Math.max(0,Math.min(1,w1+w2*.5)),fade=1/Math.pow(1+longitudinal*2.6,1.25),intensity=(ia*(w0+w1)+ic*w2)*gain*fade;target.plot(x,y,-.985,{r:(ca[0]*w0+cb[0]*w1+cc[0]*w2)*intensity,g:(ca[1]*w0+cb[1]*w1+cc[1]*w2)*intensity,b:(ca[2]*w0+cb[2]*w1+cc[2]*w2)*intensity,a:1},'add');}}

/** Distort an existing scene through a projected triangular glass region. */
export function refractTriangleScreen(target:RenderTarget,a:{x:number;y:number},b:{x:number;y:number},c:{x:number;y:number},strength=5,dispersion=1.5,absorption=.82):void { const source=target.color.slice(),minX=Math.max(0,Math.floor(Math.min(a.x,b.x,c.x))),maxX=Math.min(target.width-1,Math.ceil(Math.max(a.x,b.x,c.x))),minY=Math.max(0,Math.floor(Math.min(a.y,b.y,c.y))),maxY=Math.min(target.height-1,Math.ceil(Math.max(a.y,b.y,c.y))),area=edge(a,b,c.x,c.y);if(Math.abs(area)<1e-6)return;const center={x:(a.x+b.x+c.x)/3,y:(a.y+b.y+c.y)/3};for(let y=minY;y<=maxY;y++)for(let x=minX;x<=maxX;x++){const w0=edge(b,c,x+.5,y+.5)/area,w1=edge(c,a,x+.5,y+.5)/area,w2=1-w0-w1;if(w0<0||w1<0||w2<0)continue;const edgeFade=Math.min(1,Math.max(0,Math.min(w0,w1,w2)*10)),dx=(center.x-x)*strength/Math.max(1,target.width),dy=(center.y-y)*strength/Math.max(1,target.height);const i=(y*target.width+x)*3;for(let ch=0;ch<3;ch++){const spectral=(ch-1)*dispersion,xx=Math.max(0,Math.min(target.width-1,Math.round(x+dx*target.width+spectral))),yy=Math.max(0,Math.min(target.height-1,Math.round(y+dy*target.height))),si=(yy*target.width+xx)*3+ch;target.color[i+ch]=source[si]*absorption*edgeFade+source[i+ch]*(1-edgeFade);}}}
function edge(a:{x:number;y:number},b:{x:number;y:number},x:number,y:number):number{return(b.x-a.x)*(y-a.y)-(b.y-a.y)*(x-a.x)}
