// The AI Gateway model catalog for the match-setup picker, loaded from the baked
// assets/models.json (generated by src/tools/fetch-models.ts). Grouped by
// creator so the modal can offer creator → model selection rather than one flat
// list of ~200 combos. Loaded synchronously at import (small JSON, offline).
import { readFileSync } from 'node:fs';
import { asset } from '../assets.ts';

export interface ModelInfo {
  id: string; // "creator/model" gateway slug
  name: string; // display name
}
export interface CreatorInfo {
  slug: string;
  name: string; // display label
  models: ModelInfo[];
}

const catalog: { creators: CreatorInfo[] } = JSON.parse(readFileSync(asset('models.json'), 'utf8'));

// Creators hidden from the picker because their models don't actually play through the
// gateway right now (verified via src/tools/model-probe.ts): `arcee-ai` is gated
// behind a separate access profile, `meituan` reports "Unsupported model", and
// `sakana` hangs past the request timeout. Drop a slug from this set once it works.
// Direct lookups (modelsFor / modelName) still resolve these, so the probe can
// re-test them by name; only the listed/selectable set excludes them.
const UNSUPPORTED = new Set(['arcee-ai', 'meituan', 'sakana']);

// Selectable creators (picker + probe sweep) — excludes the unsupported ones.
export function creators(): CreatorInfo[] {
  return catalog.creators.filter((c) => !UNSUPPORTED.has(c.slug));
}
export function modelsFor(slug: string): ModelInfo[] {
  return catalog.creators.find((c) => c.slug === slug)?.models ?? [];
}
export function creatorName(slug: string): string {
  return catalog.creators.find((c) => c.slug === slug)?.name ?? slug;
}
export function modelName(id: string): string {
  for (const c of catalog.creators) {
    const m = c.models.find((mm) => mm.id === id);
    if (m) return m.name;
  }
  return id;
}
