// The AI Gateway model catalog for the match-setup picker, loaded from the baked
// assets/models.json (generated by src/tools/fetch-models.ts). Grouped by
// creator so the modal can offer creator → model selection rather than one flat
// list of ~200 combos. Loaded synchronously at import (small JSON, offline).
import { readFileSync } from 'node:fs';
import { asset } from '../assets.ts';

export interface ModelInfo {
  id: string; // "creator/model" gateway slug
  name: string; // display name
}
export interface CreatorInfo {
  slug: string;
  name: string; // display label
  models: ModelInfo[];
}

const catalog: { creators: CreatorInfo[] } = JSON.parse(readFileSync(asset('models.json'), 'utf8'));

// Compatibility policy (AIG-183). Selectable models play through the ModelPlayer
// fallback ladder automatically — native structured output → plain-text soft parse →
// 2nd-LLM normalization (see normalizerModel) → a visibly-diagnosed random legal move
// as the last resort. So a model that lacks structured output (e.g. thinkingmachines/
// inkling) stays selectable and still plays via a lower rung, rather than being hidden
// or shown a warning. Only creators that don't play through the gateway AT ALL are
// hidden here; the reproducible audit is `src/tools/model-compat-report.ts`.
//
// Currently hidden (verified via the probe / report): `arcee-ai` is gated behind a
// separate access profile, `meituan` reports "Unsupported model", and `sakana` hangs
// past the request timeout. Drop a slug once it works. Direct lookups (modelsFor /
// modelName) still resolve these, so the tools can re-test them by name; only the
// listed/selectable set excludes them.
const UNSUPPORTED = new Set(['arcee-ai', 'meituan', 'sakana']);

// Selectable creators (picker + probe sweep) — excludes the unsupported ones.
export function creators(): CreatorInfo[] {
  return catalog.creators.filter((c) => !UNSUPPORTED.has(c.slug));
}
export function modelsFor(slug: string): ModelInfo[] {
  return catalog.creators.find((c) => c.slug === slug)?.models ?? [];
}
export function creatorName(slug: string): string {
  return catalog.creators.find((c) => c.slug === slug)?.name ?? slug;
}
export function modelName(id: string): string {
  for (const c of catalog.creators) {
    const m = c.models.find((mm) => mm.id === id);
    if (m) return m.name;
  }
  return id;
}

// The structured-output-capable model used for ModelPlayer's normalization rung
// (AIG-183) — the last resort BEFORE a random legal move, invoked only after the
// native-structured and deterministic-soft-parse rungs have failed. Kept as a fast,
// cheap, reliably-structured model so the rare rescue call is light. Verified to do
// structured output on the standard team; if it's itself unreachable the rung just
// errors and we fall back to random, so enabling it never makes things worse.
//
// Automatic by default (a recovered real move beats a silent random one). Override
// via ARCADE_NORMALIZE: a slug swaps the model; "0"/"off"/"false"/"none" disables
// the rung entirely (chess and poker then random-fallback as before).
const DEFAULT_NORMALIZER = 'anthropic/claude-haiku-4.5';
export function normalizerModel(): string | undefined {
  const v = process.env.ARCADE_NORMALIZE?.trim();
  if (v && /^(0|off|false|no|none)$/i.test(v)) return undefined;
  if (v && !/^(1|on|true|yes)$/i.test(v)) return v; // an explicit override slug
  return DEFAULT_NORMALIZER;
}
