// One-off generator: converts the public-domain font8x8 bitmap font into our
// src/engine/font8x8.ts data module. Run once (not part of the app build):
//
//   curl -fsSL https://raw.githubusercontent.com/dhepper/font8x8/master/font8x8_basic.h -o reference/font8x8_basic.h
//   pnpm exec tsx src/tools/gen-font.ts
//
// font8x8 stores 8 bytes per glyph (top→bottom); within each byte the LSB is
// the leftmost pixel. We emit, per printable char, 8 left-to-right '0'/'1' rows.
import { readFileSync, writeFileSync } from 'node:fs';

const src = readFileSync('reference/font8x8_basic.h', 'utf8');
const re = /\{([^}]*)\}\s*,\s*\/\/\s*U\+([0-9A-Fa-f]{4})/g;

const entries: string[] = [];
let m: RegExpExecArray | null;
while ((m = re.exec(src)) !== null) {
  const cp = parseInt(m[2], 16);
  if (cp < 0x20 || cp > 0x7e) continue;
  const bytes = m[1]
    .split(',')
    .map((s) => s.trim())
    .filter(Boolean)
    .map((s) => parseInt(s, 16));
  if (bytes.length !== 8) continue;
  const rows = bytes.map((byte) =>
    Array.from({ length: 8 }, (_, x) => ((byte >> x) & 1 ? '1' : '0')).join(''),
  );
  const char = String.fromCharCode(cp);
  entries.push(`  ${JSON.stringify(char)}: [${rows.map((r) => `'${r}'`).join(', ')}],`);
}

const out = `// Generated by src/tools/gen-font.ts from the public-domain font8x8 bitmap font
// (Daniel Hepper / Marcel Sondaar / IBM VGA, Public Domain). Do not edit by hand.
// Each printable ASCII char maps to 8 left-to-right '0'/'1' rows (row 0 = top).
export const FONT: Record<string, string[]> = {
${entries.join('\n')}
};
`;
writeFileSync('src/engine/font8x8.ts', out);
console.log(`wrote src/engine/font8x8.ts with ${entries.length} glyphs`);
